Extract all GH issue for ingestion
astronomer/ask-astro pull request #182
Opened 2023-12-01 05:39 UTC by pankajastro

2023-12-01 06:04 UTC, Lee-W approved these changes

2023-12-01 06:22 UTC, sunank200 requested changes
We should do the following before we merge this change:
1. Run a fresh bulk ingestion DAG and run this DAG as well in Dev database.
2. Request @vatsrahul1001 to test this to make sure the performance has not degraded. This should be deployed in dev slackbot.
Blocking the merge till then

2023-12-04 11:31 UTC, pankajastro commented
@vatsrahul1001 can you please test this once from your side?

2023-12-11 09:57 UTC, sunank200 approved these changes

2023-12-13 05:59 UTC, merged