[WIP] Ingest astronomer-provider-html docs
astronomer/ask-astro pull request #199
Opened 2023-12-01 13:37 UTC by pankajastro

2023-12-11 09:56 UTC, sunank200 requested changes
@pankajastro can you add this change to bulk load DAG as well?

2023-12-13 13:16 UTC, sunank200 requested changes

2023-12-13 13:16 UTC, sunank200 commented on airflow/include/tasks/extract/astro_sdk_docs.py
> +    print("******ingesting****")
it should be logging instead of print

2023-12-13 13:16 UTC, sunank200 commented on airflow/include/tasks/extract/astro_sdk_docs.py
> +    new_urls = [url for url in urls if not version_pattern.search(url)]
This should just pick the latest one.

2023-12-13 13:48 UTC, pankajastro commented on airflow/include/tasks/extract/astro_sdk_docs.py
> +    new_urls = [url for url in urls if not version_pattern.search(url)]
change to match "stable"

2023-12-18 09:06 UTC, sunank200 approved these changes

2023-12-18 09:06 UTC, sunank200 commented on airflow/include/tasks/extract/astro_sdk_docs.py
> +    base_url = "https://astro-sdk-python.readthedocs.io/en/stable/"
This is a better approach

2023-12-18 09:10 UTC, merged