Fix No Feedback Defaults to 0 Score (Negative Feedback) in Snowflake
astronomer/ask-astro pull request #304
Opened 2024-02-23 01:42 UTC by davidgxue

closes #291

2024-02-23 03:43 UTC, pankajastro approved these changes

2024-02-23 05:50 UTC, pankajkoti approved these changes

2024-02-23 07:30 UTC, Lee-W commented on airflow/dags/metrcis/load_firestore_to_snowflake.py
> +from typing import Optional
```suggestion
```

2024-02-23 07:30 UTC, Lee-W commented on airflow/dags/metrcis/load_firestore_to_snowflake.py
> +        rows: list[tuple[str, Optional[int], bool, datetime]] = []
```suggestion
        rows: list[tuple[str, int | None, bool, datetime]] = []
```

2024-02-23 15:06 UTC, Lee-W approved these changes

2024-02-24 17:28 UTC, pankajastro approved these changes

2024-02-29 22:25 UTC, jlaneve approved these changes

2024-03-01 11:43 UTC, sunank200 requested changes
Can you add the test cases for the change

2024-03-01 18:07 UTC, davidgxue commented
> Can you add the test cases for the change

There was no unit test for this original file to begin with. In fact, there isn't a single unit test for the entire airflow code when the previous team worked on this. I can start an initiative for better test coverage to add them, but due to the urgency of this bug fix PR, I don't think it makes sense to write all the unit tests here.

2024-03-01 20:24 UTC, sunank200 approved these changes

2024-03-01 21:50 UTC, merged